spring.application.name=rightservice
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5434/rights
spring.datasource.username=aria
spring.datasource.password=aria

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true