spring.application.name=catalogservice
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/catalog
spring.datasource.username=aria
spring.datasource.password=aria

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

aria.minio.url=http://localhost:9000
aria.minio.accessKey=minio
aria.minio.secretKey=minio12345
aria.minio.bucket=aria-audio

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

aria.rights.baseUrl=http://rights-service:8082

aria.jwt.secret=11111111112222222222333333333344
aria.jwt.expMinutes=120
aria.jwt.issuer=aria
aria.rights.url=${ARIA_RIGHTS_URL:http://localhost:8082}
aria.google.clientId=276354781244-64oph92hm2d5mia0b4n43fkcmok49p41.apps.googleusercontent.com