spring.application.name=royaltiesservice
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5435/royalties
spring.datasource.username=aria
spring.datasource.password=aria

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true